---
language: go
sudo: false
go: 1.12
env:
  global:
    - GO111MODULE=on
script:
  - make deps
  - make vet
  - make coverage TAGS=integration
after_success:
  - bash <(curl -s https://codecov.io/bash)
